name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-native:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            cmake_preset: cl-x64-debug
            compiler: cl
          - os: windows-latest
            cmake_preset: cl-x64-release
            compiler: cl
          - os: ubuntu-latest
            cmake_preset: clang-x64-release
            compiler: llvm-22.0.0
          - os: ubuntu-latest
            cmake_preset: gcc-x64-release
            compiler: gcc-16

    uses: ./.github/workflows/cmake-build.yml
    with:
      os: ${{ matrix.os }}
      cmake_preset: ${{ matrix.cmake_preset }}
      compiler: ${{ matrix.compiler }}

  build-emscripten:
    uses: ./.github/workflows/cmake-build.yml
    with:
      os: ubuntu-latest
      cmake_preset: emscripten-wasm-release
      use_emcmake: true
      build_container: emscripten/emsdk:latest